const quotes = {
  "happy" : ["happier.jpg", "happy.jpg", "happybook.jpg", "helenhap.jpg"],
  "sad" : [],
  "mad",
  "brave",
  "embarrassed",
  "friendly",
  "sorry",
  "disappointed",
  "frustrated",
  "silly",
  "hopeful",
  "left-out",
  "excited",
  "jealous",
  "curious",
  "cranky",
  "insecure",
  "greatful",
  "loved",
  "guilty",
  "uncomfortable",
  "shy",
  "hurt",
  "surprised",
  "scared",
  "kind"
}
